### ISSUE TITLE
@index为undefined

### ISSUE THREAD

**Issue by kedadiannao220** [daaain/Handlebars#100]
{{#each array}}
  {{log @index}}
{{/each}}

i logged @index, its value is undefined;
also @key @last.....

**Comment by daaain** [comment]
Hey @kedadiannao220,

I'm not sure if I understand the issue, are you seeing this output in your browser console?

This package only provides syntax highlighting for Handlebars in text editors, so the compilation happens somewhere else in your tooling.

I'm close this issue as I think it's outside of scope, but feel free to comment and in case it's something this library is breaking I'm happy to reopen.

**Comment by kedadiannao220** [comment]
hi @daaain,
I am a Handlebars user,  other syntaxes used good, like if、else、or、eq; only these @index @key @last have problems, i don't know why, i checked the chrome console, it logged undefined;

**Comment by daaain** [comment]
Hey @kedadiannao220,

This repository if only for the syntax colouring in code editors, so it has nothing to do with what you see on the browser console.

The library which compiles Handlebars is here: https://stackoverflow.com/questions/tagged/handlebars.js

But this question you should really post on Stackoverflow: https://stackoverflow.com/questions/tagged/handlebars.js

Preferably with a code example on JSFiddle which demonstrates the error.
