### ISSUE TITLE
[vscode] strange behaviour with else if and () subexpressions

### ISSUE THREAD

**Issue by Frozenfire92** [daaain/Handlebars#101]
![Screen Shot 2019-03-23 at 4 02 34 PM](https://user-images.githubusercontent.com/5893112/54870404-1b913100-4d85-11e9-97be-3293f63c6b12.png)

My investigation led me to this line

https://github.com/daaain/Handlebars/blob/790f2b0222098a3a236bd9e91bb9a039eeca4d8e/grammars/Handlebars.json#L634

it appears the regex needs two things
- the optional ` if` to be added into the same token as the `else`
- add support for `()` wrapped sub expressions. I suspect just adding these characters to `[-a-zA-Z0-9_\\./]` would suffice. It likely will also need support for spaces

**Comment by daaain** [comment]
Thanks a lot for the report and even more so for finding where to update the code!

I managed to add support for subexpressions, but I'm not 100% sure how to get the changes picked up by the VSCode team so I asked them, let's see what they say: https://twitter.com/daaain/status/1117115077654712320

**Comment by daaain** [comment]
This should be merged now: https://github.com/microsoft/vscode/issues/73757
