### ISSUE TITLE
How to set key binding for comments? (Sublime Text)

### ISSUE THREAD

**Issue by brandonjp** [daaain/Handlebars#104]
I see the note in README that you can set a key binding for comments: https://github.com/daaain/Handlebars/blame/master/README.md#L7

Is there a command I can assign to toggle handlebars comments when I'm inside an html file?  (When not using handlebars syntax on the file?)

Thanks!

**Comment by daaain** [comment]
Hey @brandonjp,

I don't think it's possible to use the functionality of this package unless you switch the HTML file extension association to it. That said, I haven't used Sublime much for years (more into VSCode nowadays) so I might be wrong.
