### ISSUE TITLE
CMD + Alt + . Keyboard Shortcut is Disabled

### ISSUE THREAD

**Issue by JohnONolan** [daaain/Handlebars#23]
I can't figure out why - but when I have a file type set to Handlebars, the standard Sublime keyboard shortcut of `CMD + Alt + .` - which is the shortcut for `Edit > Tag > Complete Tag` does not function at all. 

I've been able to verify this with a couple of people to ensure it's not just my environment, but I'm not sure what other info I can provide to debug.

I'm on Sublime 2.0.2 build 2221

**Comment by thedamon** [comment]
Very weird indeed.
I used the the [Laravel Blade Syntax Highlighter](https://github.com/Medalink/laravel-blade) previously and it does not mess up the normal close tag shortcut...

**Comment by daaain** [comment]
Thanks for the tip @thedamon, I just had a look.

One thing which I noticed is that in the README the author mentions that the [package is incompatible with the HTML5 one](https://github.com/Medalink/laravel-blade#incompatible-plugins), hmm, I wonder if I should be testing with and without that one.

But anyway, it seems that this package is also doing the approach I'm trying to avoid by importing the entire [HTML](https://github.com/Medalink/laravel-blade/commit/6d8d097b806b37f6d0cc7d2a52f6c4a0a111ed4f) and later [PHP package](https://github.com/Medalink/laravel-blade/commit/1d6f565784901841e6838e4cc51eaccaf597bc1b) so now there's 3500+ LOC to maintain. Also no idea how ST deals with the execution of syntax packages, but having to crunch through that much code can't be good for performance either.

Anyway, I'll leave this issue open for now hoping that one day it'll become clear what's exactly causing the problem.

**Comment by thedamon** [comment]
I will say that while I'm not using the blade syntax much anymore I did find that package to be a little buggy and kept breaking.. So hearing that abt the preloading and wanting to avoid it does make sense

**Comment by daaain** [comment]
I just had a look and it seems installing Tag package fixes the keyboard shortcut even without having to manually add any binding. Since there's a simple and quick workaround (which I now added to the README) I'm very unlikely to give time to this fix, so closing the issue. PRs are still welcome though!
