### ISSUE TITLE
Emmet doesn't work within <script> template

### ISSUE THREAD

**Issue by arechsteiner** [daaain/Handlebars#27]
I have the following template within a server side handlebars template, `index.hbs`:

    <script type="text/x-handlebars-template" id="question-form-template">
      <p>\{{ question }}</p>
    </script>

While syntax highlighting works, Emmet doesn't. I'm not sure how to make it work. I've tried this solution on handlebars.tmlanguage:

http://www.sublimetext.com/forum/viewtopic.php?f=2&t=4057

To no avail, unfortunately.

Note: I'm using Handlebars both on the server (via express-hbs) as well as on the front end with Backbone, hence a Handlebars template within a Handlebars template :)

**Comment by daaain** [comment]
I just had a look, and it seems Emmet is working within script tags, at least a text selection one I tried does.

Can you please confirm @arechsteiner if it works for you now? If not, can you please let me know what Emmet functionality you're trying to use?

**Comment by arechsteiner** [comment]
@daaain I've since switched to Vim, so I'm not using this plug-in any more.

**Comment by daaain** [comment]
Oh well, in that case I'm definitely closing this issue down :)

Thanks for the heads up!
