### ISSUE TITLE
HTML tags don't match

### ISSUE THREAD

**Issue by Frozenfire92** [daaain/Handlebars#48]
.hbs file

![screen shot 2014-08-08 at 10 30 10 am](https://cloud.githubusercontent.com/assets/5893112/3857123/27d1f75a-1f00-11e4-82fa-f65eb2bc04e9.png)

.html file

![screen shot 2014-08-08 at 10 29 59 am](https://cloud.githubusercontent.com/assets/5893112/3857126/2d0f0fe6-1f00-11e4-94c3-346c18028b14.png)

**Comment by daaain** [comment]
I've added the BracketHighlighter package workaround to the README (thanks @designorant). Closing the issue as it's very unlikely that I'll ever get around to work on this given that there's a perfect solution (and this issue is referenced from the README now), but of course PRs are still welcome.

**Comment by mmcintyre123** [comment]
The only downside to this is that in order for the BracketHighlighter: Select Bracket Content command to work the cursor has to be on the tag rather than on the tag content you want to select.  ctrl+shift+a in HTML works when the cursor is on the tag content.
