### ISSUE TITLE
Tag auto-closing

### ISSUE THREAD

**Issue by baudoin** [daaain/Handlebars#49]
Minor detail, but I noticed that in HTML files, tags will close when typing < after the opening tag. This doesn't happen in HBS files though using the Handlebars syntax.

![div](https://cloud.githubusercontent.com/assets/585033/4290013/4b0f4020-3db8-11e4-9716-03d2fe4cb0e2.gif)

**Comment by iameli** [comment]
Finding the [Tag](https://github.com/titoBouzout/Tag) package to be a totally acceptable substitute here. Thus far indistinguishable from the native Sublime functionality except that it works with this package and some other third-party packages.

**Comment by daaain** [comment]
I've added the Tag package workaround to the README (thanks @iameli). Closing the issue as it's very unlikely that I'll ever get around to work on this given that there's a perfect solution, but of course PRs are still welcome.

**Comment by GriffinSauce** [comment]
Apparently the Tag package has been removed from packagecontrol and even after manual install it still doesn't work. Does anyone know of a different workaround/fix by now?

Sorry for resurrecting this ancient issue ;)

**Comment by thekeele** [comment]
@GriffinSauce 

Ran across Tag missing from Package Control as well. I was able to get it working manually though.

- Download Tag | https://github.com/titoBouzout/Tag
- Unzip and move folder to ~/.config/sublime-text-3/Packages/
- Make sure the folder is named **Tag**
- Open Package Control Settings - User
- Add **"Tag"** to the "installed_packages" array
- Restart Sublime

Enjoy HTML tag closing goodness.

**Comment by GriffinSauce** [comment]
Well apparently I screwed up because that works!
Thanks for the step by step @thekeele!

**Comment by MKorostoff** [comment]
After following the above steps, I now get this result in every time I boot up sublime:

<img width="266" alt="tag" src="https://user-images.githubusercontent.com/1197335/58482422-55d3d180-812c-11e9-8552-ae6768b8c408.png">

**Comment by daaain** [comment]
> After following the above steps, I now get this result in every time I boot up sublime:
> 
> <img alt="tag" width="266" src="https://user-images.githubusercontent.com/1197335/58482422-55d3d180-812c-11e9-8552-ae6768b8c408.png">

Sorry to hear that @MKorostoff, maybe try to open an issue on that repo?

Or have a look in Package Control, there might be other packages which do the same thing, maybe this: https://packagecontrol.io/packages/Auto%20Close%20HTML%20Tags
