### ISSUE TITLE
Variable/expression as tag name

### ISSUE THREAD

**Issue by stevenvachon** [daaain/Handlebars#55]
```handlebars
<{{tag}} attr="asdf">asdf</{{tag}}>
```

GitHub uses this project/repo for its Handlebars highlighting in case you didn't know, so the above code block will reflect the status of this error.

**Comment by daaain** [comment]
Wow, I had no idea! Do they say this anywhere? :)

The problem does show up locally too, so will try to fix it soon (just in the middle of a house move).

**Comment by stevenvachon** [comment]
https://github.com/github/linguist/tree/master/vendor/grammars :) search for "handlebars" and it links to this repo

Awesome, congrats! And thanks!

**Comment by daaain** [comment]
I just pushed a fix for this, curious how long will it take for Github to pick the change up for the highlight grammar :)

**Comment by stevenvachon** [comment]
:) They'd told me to alert them when it was updated, so it shouldn't be a long wait.

**Comment by arfon** [comment]
This fix went live on GitHub this morning.

**Comment by stevenvachon** [comment]
Hmm, the last `>` is green when it probably shouldn't be. @daaain

It's much better than before though :+1:

**Comment by daaain** [comment]
@stevenvachon I noticed :( but was struggling a bit with the inexplicable inclusion by the regex and had to give up on this solution as an incremental step.

If you're good with regex please take a look at these two blocks, top one is capturing any non-standard tag, bottom one is this tokenised and the only difference is adding the curly braces so not sure what's going on, but I might be missing something obvious: https://github.com/daaain/Handlebars/blob/master/Handlebars.JSON-tmLanguage#L260-L295
