### ISSUE TITLE
Wonky curly brace matching within a block

### ISSUE THREAD

**Issue by appleton** [daaain/Handlebars#56]
![screen recording 2015-02-26 at 12 47 pm](https://cloud.githubusercontent.com/assets/241576/6392157/9fc97a54-bdb5-11e4-9509-205f87a40045.gif)

I'm seeing some funny curly brace matching behaviour when I try to add them within a block containing HTML. I think the gif describes the issue pretty well.

Please let me know if I can do anything else to help diagnose the issue and thank you for a really great plugin!

**Comment by daaain** [comment]
Hey,

This seems to be the same issue as #52.

If you have a bit of time, what would be really helpful is if you could test to see at which commit this behaviour was introduced to narrow things down.

**Comment by appleton** [comment]
I read the open issues before submitting this and *still* didn't notice that it's already been reported! I'll close this and make an attempt to isolate if I get the opportunity.

**Comment by daaain** [comment]
Well to be fair the title of that issue wasn't really clear, so just rewrote it :)
