### ISSUE TITLE
Question - Using normal html comments

### ISSUE THREAD

**Issue by danjford** [daaain/Handlebars#59]
Is there a way so that I can use normal commenting `<!---->` instead of the handlebars one?

**Comment by daaain** [comment]
You mean when pressing the shortcut `CMD + /` or `CTRL + /`?

If yes then you'd need to change the behaviour in your local package, see https://github.com/daaain/Handlebars/blob/master/Comments.tmPreferences#L17 and https://github.com/daaain/Handlebars/blob/master/Comments.tmPreferences#L23.

**Comment by daaain** [comment]
Closing as requester disappeared and this as it's not something which has one simple solution.

**Comment by cvax** [comment]
Hi,

Changing those lines to `&lt;` and `&gt;` doesn't work though for some reason. I changed them, saved the Comments.tmPreferences file, but all `CTRL+/` commenting is still showing up as `{{!-- --}`
