### ISSUE TITLE
'else' gets wrong treatment

### ISSUE THREAD

**Issue by louwers** [daaain/Handlebars#61]
![screen shot 2015-05-26 at 16 06 44](https://cloud.githubusercontent.com/assets/649392/7814263/4199061e-03c1-11e5-9d07-b2a837a6fd25.png)

`else` is part of the `{{#if ...}}` syntax, so it would be consequent if it were the same color, no?

**Comment by daaain** [comment]
Good point, fixed :)

**Comment by louwers** [comment]
Brilliant! Thanks a bunch!

**Comment by louwers** [comment]
There still seem to be problems if you use an `{{#unless}}`-block inline.

![screen shot 2015-06-22 at 14 56 24](https://cloud.githubusercontent.com/assets/649392/8282250/7915579e-18ef-11e5-8689-472a17171cf2.png)

**Comment by daaain** [comment]
Right, had to enable this inside quotes, fixed now by 05d8d217d18f0d0b74fde52e596fd9875bd5ad08
