### ISSUE TITLE
Atom not working

### ISSUE THREAD

**Issue by tomitrescak** [daaain/Handlebars#62]
How do you make this work in atom?
Activating your plugin does not show up Handlebars in the list of possible editors.

**Comment by daaain** [comment]
Which operation system are you using?

It's definitely working for me:
![screen shot 2015-05-27 at 18 47 44](https://cloud.githubusercontent.com/assets/69962/7843343/ebed7f5c-04a0-11e5-9e87-4778b1e91b4a.png)

**Comment by tomitrescak** [comment]
OS X, same as you. When I click on the bottom right kf the window to change from html to handlebars it does not I'm up in the list.

**Comment by daaain** [comment]
Hmm, strange...

Are you using the latest version of OS X (10.10.3) and Atom (0.202.0)?

Can you see the package installed and enabled under Community Packages?

![image](https://cloud.githubusercontent.com/assets/69962/7857201/925b98a8-0526-11e5-81be-7ff9fd671f97.png)

**Comment by thewalkingtoast** [comment]
I am experiencing the same issue. I did have https://github.com/Sneagan/atom-handlebars installed but disabled. I removed both and reinstalled this one, no luck (restarting Atom in-between). I am using OS X 10.10.3 and Atom 0.204.0. Let me know if there anything else I can do to assist. Thank you!

**Comment by tomitrescak** [comment]
Same configuration for me.

**Comment by daaain** [comment]
OK, I found the problem, apparently Atom is not checking out the symlink to the grammar syntax JSON file so as far as it's concerned it's an empty package. The reason it worked for me is because I had my local development folder symlinked into the Atom packages folder.

Anyway, as a workaround I'll just duplicate the file for now until there's a cleaner solution in the build system in Sublime's AAAPackageDev: https://github.com/SublimeText/AAAPackageDev/issues/59

**Comment by daaain** [comment]
@tomitrescak @thewalkingtoast please update to v1.1.1 and let me know if that fixes the issue for you!

**Comment by thewalkingtoast** [comment]
@daaain That did. Thank you! I had to restart Atom (updating wasn't enough on its own) but everything is great now. :+1:

**Comment by tomitrescak** [comment]
Works for me as well. Thanks for the fix.

On Mon, 1 Jun 2015 at 5:53 am Adam Radabaugh <notifications@github.com>
wrote:

> @daaain <https://github.com/daaain> That did. Thank you! I had to restart
> Atom (updating wasn't enough on its own) but everything is great now. [image:
> :+1:]
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/daaain/Handlebars/issues/62#issuecomment-107240060>.
>
-- 
~
Tomi Trescak / Researcher  tomi.trescak@gmail.com / 0487 261 213

**Comment by daaain** [comment]
Closing as it seems everyone's Atom is happy now :)
