### ISSUE TITLE
Error message: unable to load Handlebars.tmLanguage

### ISSUE THREAD

**Issue by ijdickinson** [daaain/Handlebars#64]
I'm using Sublime Text 3 build 3083 on Ubuntu. In recent days when I start the editor, I'm getting an error message:

    error: Error loading syntax file "Packages/Handlebars/Handlebars.tmLanguage": Unable to open Packages/Handlebars/Handlebars.tmLanguage

I've tried uninstalling and re-installing the Handlebars package via package manager, but I still get the same error.

Version number is `2015.05.31.18.29.42`. What other information would be helpful for me to supply?

**Comment by daaain** [comment]
Hmm, it's looking for the file in the wrong place, I recently moved the `.tmLanguage` file under `/grammars` as part of making the package work with Atom, but Sublime has no problem picking up the file from the subdirectory on my Mac. I even have the same build as you.

Do you have anything custom in your settings file?

**Comment by dadamssg** [comment]
+1 having this same problem.

**Comment by daaain** [comment]
Thanks for the followup @dadamssg!

@ijdickinson I'm wondering if maybe it's some cache issue? Can you please try to uninstall the package once again, but before reinstalling taking a look in your packages folder, including `Cache` to make sure that nothing is lingering?

**Comment by ijdickinson** [comment]
OK, I'll try that.

**Comment by ijdickinson** [comment]
OK, so this time uninstalling and reinstalling did work. I didn't see anything in my cache, but the problem on starting up has now gone away. Thank you!

**Comment by daaain** [comment]
Phew, great! Glad that it worked out, was getting a bit worried :)
