### ISSUE TITLE
Handlebars not appearing in Sublime package list

### ISSUE THREAD

**Issue by PatrickKing** [daaain/Handlebars#65]
Handlebars isn't showing up in package control's list of packages for me. Any ideas? I'm running Sublime build 3083, Ubuntu 12.04.

**Comment by daaain** [comment]
Hmm, could this be related to the issue in #64 ?

Have you had it installed earlier or is this the first time?

**Comment by PatrickKing** [comment]
This is my first time trying to install it on my home (ubuntu) system... though, Handlebars showed up and installed fine on my work system, which is running OSX 10.9. I can take a look at the cache folder on my ubuntu system tonight and see if there's anything suspicious.

**Comment by PatrickKing** [comment]
You were right, there was an old corrupted install of handlebars from some time ago. Some combination of deleting cache and extension files, using package control to remove the extension, and restarting sublime allowed me to make a fresh install, which seems to be working!
