### ISSUE TITLE
Force priority over default "(HTML) Handlebars"

### ISSUE THREAD

**Issue by tomitrescak** [daaain/Handlebars#69]
Hi, sorry for asking in your issues, but do you know how can I force to load your handlebars over the original "(HTML) handlebars", when opening handlebars file? My HTML files are handlebars (Meteor), so I have added to my init script following:

```coffee
fileTypes =
    '.html':'text.html.handlebars'
```

**Comment by daaain** [comment]
Hey,

No worries at all :)

This is for Sublime Text, right?

I'm not sure if there's a good project level override, but I just use the "Open all with current extension as..." context menu in the bottom right corner to set up whatever needs to handle the extension. Obviously this will change it for all projects, but it's easy to change around.

Does this help?

**Comment by tomitrescak** [comment]
Sorry, I meant Atom ;)

**Comment by daaain** [comment]
Ah right, with Atom I just disabled the built in Mustache package and that fixed it. Maybe I should put this into the Readme!

**Comment by daaain** [comment]
Finally got around to add a note about this in the README, closing.
