### ISSUE TITLE
Build system menu item in ST3

### ISSUE THREAD

**Issue by deconvolved** [daaain/Handlebars#73]
When installed for Sublime Text 3, an item named '.sublime-build' is added to the build system menu (Tools > Build System).

Running 'zip -d Handlebars.sublime-package ".sublime-build"' resolved this issue for me. I don't know if this breaks anything else, but highlighting still seems to work properly.

This is for version v2015.09.05.15.51.58 with Sublime Text 3, Build 3083.

**Comment by daaain** [comment]
Hmm, I'm not sure if I follow you, but this package does have a `.sublime-build` file and it's only needed for development so you can definitely live without it :)

**Comment by deconvolved** [comment]
In Sublime Text 3 the `.sublime-build` file is being interpreted as a build system that should be made available to the user via the menu. After the package is installed, a build system option named `.sublime-build` appears in the menu under `Tools > Build System` along with `Python`, `Ruby`, etc.

In other words, instead of staying hidden away for development, the file is triggering the creation of a new build system option for regular users. And one with a broken name in that it gives no indication what it is for (the name in the menu is literally `.sublime-build`).

**Comment by daaain** [comment]
Aaah, I see now, good spot! Thanks so much for reporting!

I've just done a bit of research and couldn't find any option to hide or rename the option from the `.sublime-build` file itself.

The only thing I can think of is to maybe use Package Control APIs and automatically delete the file post install: https://packagecontrol.io/docs/events

I don't use Handlebars much these days and have very little time to maintain this package, would you be up for giving this a try and submitting a PR?

**Comment by daaain** [comment]
Added a note about this issue and the workaround in the README, closing for now as programatically deleting the file sounds like a complicated solution.
