### ISSUE TITLE
Feature request: {{else if}} helper syntax highlighting

### ISSUE THREAD

**Issue by Nibblesh** [daaain/Handlebars#75]
else if is supported in handlebars 3+ and isn't getting syntax highlighting

**Comment by hlvnst** [comment]
I was just working on some Handlebars, and it's a simple fix, so here you go.

**Comment by daaain** [comment]
Thanks for the heads up @Nibblesh and as usual thanks so much for the implementation @hlvnst, you're a great community to maintain a package for :heart:

**Comment by Nibblesh** [comment]
Really fast turnover, thanks and great job guys
