### ISSUE TITLE
Weird behavior on block helper attributes

### ISSUE THREAD

**Issue by victorwpbastos** [daaain/Handlebars#77]
I'm having weird colors on block helpers attributes:

![image](https://cloud.githubusercontent.com/assets/1017515/12429373/0561b27e-bed1-11e5-9e3f-f33a25eb8b17.png)

Inline helpers is normal. In block helpers only the first attribute is colored fine. Any ideas?

**Comment by daaain** [comment]
Good spot, added a test case to cover it:
 
![screen shot 2016-01-21 at 11 42 10](https://cloud.githubusercontent.com/assets/69962/12479627/4f830b82-c034-11e5-8c24-a04e574b6ac7.png)

**Comment by hlvnst** [comment]
I'm on a roll lately.

@daaain Question: do you tag releases directly using Git or using `apm publish`?

**Comment by daaain** [comment]
@hlvnst you're a :star:

I use `apm publish`, mostly `patch` for these small incremental fixes.

**Comment by daaain** [comment]
What am I talking about with "small incremental fix", this actually seems to also have solved named block parameters and array notation :)

Before
<img width="369" alt="screen shot 2016-01-23 at 09 57 24" src="https://cloud.githubusercontent.com/assets/69962/12529665/ec5eccd2-c1b7-11e5-9685-396eff6548e1.png">

After
<img width="376" alt="screen shot 2016-01-23 at 09 57 41" src="https://cloud.githubusercontent.com/assets/69962/12529666/f30d4ac2-c1b7-11e5-8d41-52a17ee32a02.png">

**Comment by hlvnst** [comment]
I noticed that at least named parameters incidentally improved with this fix (see commit message). Hadn't noticed the same for array notation, though. Good catch. 

Rather fortuitous, I wish all fixes were *that* easy.

**Comment by hlvnst** [comment]
Well, that only worked halfway:
```
Preparing and tagging a new version ✓
Pushing v1.4.0 tag ✓
Publishing Handlebars@v1.4.0 ✗
Creating new version failed: Git tag not found
```
It didn't push the tag upstream (to this repo), only to my fork. I pushed the tag here manually, but Atom doesn't seem to pick that up.

**Comment by daaain** [comment]
Hmm, in theory you should have rights to publish the package if you can push to the repo: https://atom.io/docs/v1.4.0/behind-atom-maintaining-your-packages#adding-a-collaborator

I do it while being on the main repo master branch, it think it'll only work from there not the fork.

**Comment by hlvnst** [comment]
> it think it'll only work from there not the fork

That seems to be the case. Next time, I'll just temporarily clone this repo and `apm publish` from there. That should do the trick.
