### ISSUE TITLE
Cannot find handlebars in package control

### ISSUE THREAD

**Issue by fabiovella83** [daaain/Handlebars#79]
The package is not present when accessing package control in Sublime 3

![screen shot 2016-01-25 at 2 19 57 pm](https://cloud.githubusercontent.com/assets/4545600/12541743/e0e7a0f0-c36e-11e5-82b3-b790ba4ead97.png)

**Comment by daaain** [comment]
Works for me on a freshly installed ST...

Can you make sure to check in the installed package list that you don't already have it?

![screen shot 2016-01-25 at 09 00 45](https://cloud.githubusercontent.com/assets/69962/12546516/39dd41ba-c342-11e5-8ca8-8841aa6b6535.png)

**Comment by fabiovella83** [comment]
Oh dear… It is already installed!! 
but cannot remember installing it!!

thank you :)

On 25 Jan 2016, at 8:02 pm, Daniel Demmel <notifications@github.com> wrote:

Works for me on a freshly installed ST...

Can you make sure to check in the installed package list that you don't already have it?

 <https://cloud.githubusercontent.com/assets/69962/12546516/39dd41ba-c342-11e5-8ca8-8841aa6b6535.png>

**Comment by daaain** [comment]
No worries, glad it was a simple fix :)
