### ISSUE TITLE
Command + Alt + . Does not complete HTML tag

### ISSUE THREAD

**Issue by specialorange** [daaain/Handlebars#80]

**Comment by daaain** [comment]
It's a known problem with simple workaround: https://github.com/daaain/Handlebars#sublime-no-auto-complete-on-closing-html-tags-23--49

**Comment by specialorange** [comment]
Didn't catch that in the search, and admittedly didn't read the front page.   Thanks and sorry :\

**Comment by daaain** [comment]
Ah, don't worry, it _is_ a bug after all :)
