### ISSUE TITLE
Problem: Mustache syntax gets applied instead of Handlebars 

### ISSUE THREAD

**Issue by ankushdharkar** [daaain/Handlebars#85]
Whenever I open up a `.hbs` file in my Ember project, it defaults to `Mustache` syntax. I have to manually change it to `handlebars` and even though I set it using `Open all with current extension as...`, it doesn't honor it next time I open a `.hbs` and defaults to `mustache` again

How do I permanently set `.hbs` to `Handlebars`?

I am using ST3 - Stable Build 3114 and I installed the `Handlebars` from the Package Control

**Comment by ankushdharkar** [comment]
What confuses me even more is the fact that I don't even have a `Mustache` syntax in my list

![screen shot 2016-06-24 at 2 35 05 pm](https://cloud.githubusercontent.com/assets/1935403/16351232/f4c6cf9e-3a18-11e6-9ac6-84b37245e280.png)

**Comment by ankushdharkar** [comment]
What confuses me even more is the fact that I don't even have a `Mustache` syntax in my list:

![screen shot 2016-06-24 at 2 37 00 pm](https://cloud.githubusercontent.com/assets/1935403/16351262/26c225f2-3a19-11e6-908a-0ff26105d224.png)

**Comment by daaain** [comment]
Hey @ankushdharkar,

I have no idea what's going on here...

Since this looks like a Sublime issue, the only things I can think of are reinstalling this package, Package Manager or Sublime itself and seeing if that helps.

Sorry that I can't be of any more help...

**Comment by ankushdharkar** [comment]
Ok. Thank you :)
