### ISSUE TITLE
Proper highlighting of '../' when accessing parent context (to pass argument)

### ISSUE THREAD

**Issue by louwers** [daaain/Handlebars#86]
It's possible to access the parent context in for example an `{{#each}}` block. This works fine with `{{../value}}`, but it doesn't work when passing a value as an argument:

```handlebars
{{> template arg=../value}}
```

In this case the `../` isn't highlighted (GitHub's Handlebars syntax highlighting seems to suffer the same fate).

**Comment by daaain** [comment]
Thanks for the report, this is fixed now!

You can have one guess which syntax definition repository does Github use for embedded Handlebars highlighting ;)
