### ISSUE TITLE
[Sublime Text 3] Handlebars Syntax not applied on .hbs file open

### ISSUE THREAD

**Issue by TylerJBrown192** [daaain/Handlebars#87]
When you open any .hbs file, the Handlebars syntax is not applied.  

- Syntax does properly apply if you manually select it.
- Issue persists even if you select View -> Syntax -> Open all with current extension as... -> Handlebars.
- The bottom right corner does say 'Handlebars' indicating that the syntax _should_ be applied. 
- If the same file is renamed to .handlebars, the syntax _does_ work on file open.

I saw other issues posted regarding this topic, but the solution to those was either file reloading or Sublime indicating the 'Mustache' syntax was being applied, which for me it does say 'Handlebars' in the bottom right corner.

Windows 7
Sublime Text Build 3114

**Comment by daaain** [comment]
Hey @TylerJBrown192,

I'm really not sure what's going on, works for me perfectly on the same OS X build.

If you look at the extension list, `.hbs` is definitely on it (as well as several others): https://github.com/daaain/Handlebars/blob/master/grammars/Handlebars.json#L862

Hmm, one idea, can you please paste the list of packages you have installed? Maybe it's a combination with another package?

**Comment by TylerJBrown192** [comment]
Yeah, this is indeed very bizarre behavior. Listed below are all installed packages:

		"AdvancedNewFile",
		"AutoFileName",
		"Autoprefixer",
		"Babel",
		"Babel Snippets",
		"BracketHighlighter",
		"C# Snippets",
		"Color Highlighter",
		"ColorPicker",
		"CSS Snippets",
		"CSS3",
		"DocBlockr",
		"Ember Template Component Split View",
		"Ember.js Snippets",
		"Git",
		"GitGutter",
		"Github Tools",
		"Handlebars",
		"HTML (C#)",
		"HTML Snippets",
		"HTML-CSS-JS Prettify",
		"HTML5",
		"HTMLAttributes",
		"JavaScript & NodeJS Snippets",
		"JavaScript Snippets",
		"jQuery",
		"JSHint",
		"JSHint Gutter",
		"Markdown Extended",
		"Markdown Preview",
		"Monokai - Spacegray",
		"Monokai Extended",
		"Monokai Neue",
		"Nodejs",
		"Package Control",
		"PackageResourceViewer",
		"Razor",
		"ReactJS",
		"ReactJS Snippets",
		"Ruby Completions",
		"Sass",
		"Seti_UI",
		"SideBarEnhancements",
		"SideBarGit",
		"Sublimerge Pro",
		"Tag",
		"Theme - Afterglow",
		"TrailingSpaces",
		"TypeScript"


Also, when I try and 'Open all with current extension as...', this is the console output if you're interested:

    Assigning hbs to syntax Packages/Handlebars/grammars/Handlebars.tmLanguage
    reloading settings Packages/User/Handlebars.sublime-settings
    warning: mnemonic t not found in menu caption Tools

**Comment by daaain** [comment]
Hmm, nothing jumps out as a potential source of conflict. Console output looks OK too.

I know it's a super annoying request, but can you try with a fresh ST install?

Or actually, have you tried reinstall the package itself and Package Manager?

**Comment by TylerJBrown192** [comment]
Didn't want to let this hang, so I'll give a quick update:

I can confirm that this issue is also happening on my 2015 MacBook Pro (OSX El Capitan & Sublime Text 3 Build 3114). By that logic, there has to be some sort of interfering package. I'm going to try and uninstall and reinstall them one by one and find the conflict, and I'll let you know.

**Comment by TylerJBrown192** [comment]
Well, I found it @daaain . It was the package [Seti_UI](https://packagecontrol.io/packages/Seti_UI).

As an experiment, after I found who the culprit was I did a completely clean reinstall of Sublime Text 3 (Preference files and all). I then installed Package Control, then Handlebars, then Seti_UI. There are still no console errors whatsoever on file open or program start.

**Comment by TylerJBrown192** [comment]
Hopefully should be fixed in Seti_UI with my [pull request here](https://github.com/ctf0/Seti_ST3/commit/a1b81142fb876b242810007a0c819050e5ec919b). I'm gonna close this issue out if that's okay!

**Comment by daaain** [comment]
Perfect, thanks a lot for the investigation!

**Comment by highpointwebdesign** [comment]
thanks Tyler for this comment:

The bottom right corner does say 'Handlebars' indicating that the syntax should be applied.

Once I told ST3 to use it as a handlebar, any future hbs file I opened, opened correctly with the right styling applied.

**Comment by Craicerjack** [comment]
I had SETI_UI but also my theme was interfering with this

**Comment by redbulled** [comment]
"Seti_Monokai" also conflicts with Handlebars package
