### ISSUE TITLE
"Partial block" syntax highlighting

### ISSUE THREAD

**Issue by aaronharder** [daaain/Handlebars#88]
Hello, and thanks for a great Sublime enhancement!

I use "partial blocks" extensively, and being a somewhat newer addition to HB, it looks like the syntax highlighting for that is not yet recognized:

http://handlebarsjs.com/partials.html#partial-block

![Partial block syntax sample](https://cloud.githubusercontent.com/assets/940080/18226983/41a6cd5a-71dc-11e6-9b7e-29d92669be19.jpg)

Don't know if it is easy to improve at all, possibly so the opening tag is highlighted like the closing tag?

Thanks again for your very helpful project!

**Comment by daaain** [comment]
Hey @aaronharder,

Really sorry that it took me ages to get back to you, but finally had a bit of time to look into this and it was a simple addition after all.

Have a nice day!
