### ISSUE TITLE
Incorrect highlighting with quotes and dollar signs

### ISSUE THREAD

**Issue by spadgos** [daaain/Handlebars#89]
This looks a little similar to #84 in its symptoms, but it's a different bug I think.

![selection_664](https://cloud.githubusercontent.com/assets/426222/19386103/b389398e-9212-11e6-971a-4e5deebfb29f.png)

When the identifier at the start begins with a `$` the string highlighting goes awry.

**Comment by spadgos** [comment]
Other weirdness too:

![selection_666](https://cloud.githubusercontent.com/assets/426222/19386744/418d00e6-9216-11e6-9172-f865a4ad1707.png)

**Comment by daaain** [comment]
Sorry for not responding for such a long time, just got around to spend a bit of time on this and managed to fix!

**Comment by spadgos** [comment]
No worries, thanks for the fix, and for the plugin in general! :bowing_man:
