### ISSUE TITLE
Deactivates Sublime's Default HTML Keyboard Shortcuts

### ISSUE THREAD

**Issue by rafegoldberg** [daaain/Handlebars#91]
> **TL;DR**→
>_using the Handlebars syntax deactivates Sublime's default HTML key bindings_

Sublime has a bunch of useful keyboard shortcuts for navigating HTML documents, i.e. _⌘⇧A_ to select the inner content of a tag. When I change the document syntax from HTML to Handlebars, all/many of these shortcuts stop working as expected (using Sublime Text 3.) Is there an easy fix that I'm missing? Anyway, this issue seems minor but it'd be super useful, at least for me/my workflow.

Anyway, just figured I'd bring it up. Thanks for all the work on this!

**Comment by daaain** [comment]
Hey @rafegoldberg,

I think this might be the same issue as #47.

Can you please have a look and see if the workaround solves your problem?

**Comment by rafegoldberg** [comment]
@daaain word, barring a more system fix `⌃`+`D` is a great workaround. alas, I already have a global shortcut mapped to that combo 😱... but still, the hint is much appreciated! closing here in favor of #47.
