### ISSUE TITLE
/ character breaks from block highlight

### ISSUE THREAD

**Issue by mixonic** [daaain/Handlebars#92]
See: https://github.com/emberjs/ember.js/issues/14224#issuecomment-265566966

> <img width="415" alt="screen shot 2016-12-07 at 4 29 06 pm" src="https://cloud.githubusercontent.com/assets/8752/20987370/50e439ac-bc9a-11e6-9d2d-889ff036569a.png">

`/some-folder/some-path` is expected to be all blue.

**Comment by mixonic** [comment]
Amazing :-) thanks @daaain!

**Comment by daaain** [comment]
No worries, it was a simple fix luckily :)
