### ISSUE TITLE
Improve coloring of block expressions

### ISSUE THREAD

**Issue by aeschli** [daaain/Handlebars#94]
```handlebars
{{#list people}}{{firstName}} {{lastName}}{{/list}}
```
`{{` and `#list` get scope `support.constant.handlebars`.
It would be nice if if the block expressions gets a scope like: 'keyword.control'. That's matching what JavaScript gives to keywords like 'if', 'while'

`firstName` gets `variable.parameter.handlebars`

**Comment by daaain** [comment]
Hey @aeschli, I finally got around to have a look at this and created a Pull request: #95.

It seems to be working, but I'm not sure if it's quite right yet. The colours with Sublime Text's default theme seem a bit off, so I'm thinking this would make sense if the closing tags (eg `/list`), inline keywords (eg `else`) and maybe even inline helpers (eg `customHelper ` in `{{customHelper "test1" 'test2' 32 true object.value}}`) were the same?

![image](https://cloud.githubusercontent.com/assets/69962/22653808/8413c1ae-ec82-11e6-984f-481b0b872e4c.png)

**Comment by aeschli** [comment]
Cool. Yes, coloring the closing tag like the block expression sounds like the right thing to me, and also the other suggestions make sense.
That said, I'm not a too deep into handlebars, I created the issue on behalf of @t-sauer. Thomas, thoughts?

**Comment by t-sauer** [comment]
I think having the same colors for inline and block expressions is totally fine (at least for me).

**Comment by daaain** [comment]
OK, I just pushed a new version, in the end I decided not to apply the same scope on inline expressions as that's shared with variables and it was just too much.

But all block expression opening and closing tags, and `else` should have the new colour now.

Let me know if it works well for you!
