### ISSUE TITLE
Not working in vscode

### ISSUE THREAD

**Issue by kuncevic** [daaain/Handlebars#97]
Just installed the extension and cant see it is working.
I've got file like `myfile.hbs` and no even syntax highlighting:

I am on `windows 10` using `vscode 1.12.1`

**Update**
Just realized that some of my `hbs` files has just `json` in it

![image](https://cloud.githubusercontent.com/assets/1283734/25768854/d5234048-324f-11e7-97e8-3191245ef163.png)

So do not have any syntax highlighting in these. 
Files where I have the real `hbr` template seams to be good

Is there anyway to get `json` highlighting as well?

**Comment by daaain** [comment]
Just out of curiosity, if the file only has JSON content then why do you use .hbs file extension?

I think JSON content should work inside a HTML / Handlebars file as there you would put it inside `<script>` and that would be treated as Javascript.

**Comment by kuncevic** [comment]
Yeah i agree that json content is should not have .hbs extension but currently it is just sort of placeholder so I will be converting that in to .hbs template. So was tining is it make scene to support json highlighting but probably not much sense.

**Comment by daaain** [comment]
Yeah, I wouldn't add code to support JSON, but as I said earlier, you could enclose your JSON in a `<script>` tag as you work with it and then it would be treated as Javascript and get highlighting.
